source 'http://rubygems.org/'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'mina'
gem 'pony'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-sqlite-adapter'
gem 'puma'
gem 'shotgun'
gem 'bcrypt'
gem 'i18n'
gem 'tilt', '~> 1.4.1'
